### ISSUE TITLE
'Store Page Fault' const value error

### ISSUE THREAD

**Issue by wangrunji0408** [char-fish-after-lunch/SystemOnCat#28]
At [CSR.scala](https://github.com/char-fish-after-lunch/SystemOnCat/blob/master/src/main/scala/core/CSR.scala) line 50:
``` scala
val SPF = 14.U(31.W)//Save page Fault
```

Should be 15.

PS. `Environment Call of H-mode` (Code 10) has been removed.

**Comment by maoyuchaxue** [comment]
Fixed.
