### ISSUE TITLE
The "I" command in the monitor do not works

### ISSUE THREAD

**Issue by benpigchu** [char-fish-after-lunch/SystemOnCat#36]
https://github.com/char-fish-after-lunch/SystemOnCat/blob/d0fcfe9d05ee8d1dca9ed5c6ea67993d0c6b1b79/prog/monitor/monitor.c#L339-L343

The `break` here in the function `unsigned inst2int(char* c)` only break inner `for` loop. Therefore `i` always equals to `INST_N` after exiting the loop, makes it imposible to parse any instructions.

**Comment by jasonyu1996** [comment]
Please note however, that a semicolon which I reckon you just overlooked ends the said `for` loop. The `break` breaks the outer loop and does the expected job.

**Comment by benpigchu** [comment]
I see.
